// Generated by Radium
import { resolve } from 'path';
import chorme from 'selenium-webdriver/chrome';
import { Builder, By, ThenableWebDriver } from 'selenium-webdriver';
import { Await } from './type';

const serviceBuilder = new chorme.ServiceBuilder(
  resolve(__dirname, './chromedriver.exe')
);
const operatePageUrl = 'https://seller.ph.shopee.cn/webchat/conversations';
const loginPageUrl =
  'https://seller.ph.shopee.cn/account/signin?next=%2Fwebchat%2Fconversations';

let driver: Await<ThenableWebDriver>;

export async function init(
  key: string,
  message: string,
  waitTime: number,
  isAgain: boolean
) {
  try {
    // promise to have one window
    if (isAgain && driver) {
      try {
        await driver.close();
        await driver.quit();
      } catch (e) {
        console.log(e instanceof Error && e.message);
      }
      driver = undefined;
    }
    console.log(isAgain, driver);
    if (!driver) {
      driver = await new Builder()
        .forBrowser('chrome')
        .setChromeService(serviceBuilder)
        .build();
    }
    await run(key, message, waitTime);
  } catch (e) {
    console.log(e instanceof Error && e.message);
    if (e instanceof Error) throw new Error(key);
  }
}

async function isLogin() {
  while ((await driver.getCurrentUrl()) !== operatePageUrl) {
    await driver.sleep(1000);
    console.log('wait login');
  }
}

async function run(key: string, message: string, waitTime: number) {
  if ((await driver.getCurrentUrl()) !== operatePageUrl) {
    await driver.get(loginPageUrl);
  }
  const durTime = waitTime * 1000;
  await isLogin();
  await driver.sleep(durTime);
  await driver.executeScript('window.scrollTo(0,0)');
  await driver.executeScript('window.scrollTo(0,0)');
  await driver.findElement(By.css('._3oQvjrwelQ')).click();
  try {
    await driver.findElement(By.css('._35r5VifQo2')).click();
  } catch (e) {
    console.warn(e instanceof Error && e.message);
  }
  await driver.findElement(By.css('._3oQvjrwelQ')).sendKeys(key);
  await driver.sleep(durTime);
  try {
    await driver.findElement(By.css('._2m-B0IaPxv')).click();
    await driver.executeScript('window.scrollTo(0,0)');
    await driver.sleep(durTime);
  } catch (e) {
    if (e instanceof Error) throw new Error(key);
  }
  try {
    try {
      const resetCommitEle = await driver.findElement(By.css('._3SRbvVaoYY'));
      if (resetCommitEle) {
        await resetCommitEle.click();
        await driver.sleep(durTime);
      }
    } catch (e) {
      console.log(e instanceof Error && e.message);
    }
    const commitTeatarea = await driver.findElement(By.css('.pmSS24qKJT'));
    await commitTeatarea.click();
    await commitTeatarea.sendKeys(message);
    await driver
      .findElement(By.css('._3kEAcT1Mk5._1UCrc0YeSY._1B6_-g44xT'))
      .click();
    await driver.executeScript('window.scrollTo(0,0)');
  } catch (e) {
    if (e instanceof Error) throw new Error(key);
  }
}
